{% set name = "nspyre" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-org/{{ name }}/refs/tags/v{{ version }}.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  noarch: python
  number: 0
  entry_points:
    - nspyre-inserv = nspyre.tools.inserv_cli:main',
    - nspyre-dataserv = nspyre.tools.dataserv_cli:main',
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    # you know it, you love it
    - numpy >=1.23.1
    # instrument server proxying
    - rpyc >=5
    # Qt/GUI
    - pyqt >=5.12
    - pyqtgraph >=0.13.1
test:
  imports:
    - nspyre
  commands:
    - nspyre-inserv --help
    - nspyre-dataserv --help
  requires:
    - pip

about:
  home: https://github.com/nspyre-org/nspyre
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pythonic Networked Scientific Experimentation Toolkit

  description: |
    nspyre is a Python package for conducting scientific experiments. It 
    provides a set of tools to allow for control of instrumentation, data 
    collection, real-time plotting, as well as GUI generation. Anyone in the 
    research or industrial spaces using computer-controlled equipment and 
    collecting data can potentially benefit from using nspyre to run their 
    experiments.
  doc_url: https://nspyre.readthedocs.io/
  dev_url: https://github.com/nspyre-org/nspyre

extra:
  recipe-maintainers:
    - mtsolmn
    - jacobfeder
