{% set name = "nspyre" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nspyre-org/nspyre/archive/v{{ version }}.tar.gz
  sha256: 50e61824a0db7f16a805d48ddf60d9d58fe0c738a490a77f57d6a804722393c3

build:
  noarch: python
  number: 2
  entry_points:
    - nspyre-dataserv = nspyre.cli.dataserv:_main
    - nspyre-inserv = nspyre.cli.inserv:_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - numpy >=1.23.0,<2.0.0
    - rpyc >=5.2.3,<6.0.0
    - pyqt >=5.12.3,<7.0.0
    - pyqtgraph >=0.13.1,<0.14.0

test:
  imports:
    - nspyre
  commands:
    - nspyre-dataserv --help
    - nspyre-inserv --help
  requires:
    - pip

about:
  home: https://github.com/nspyre-org/nspyre
  license: BSD-3-Clause
  license_file: LICENSE
  summary: (n)etworked (s)cientific (p)ython (r)esearch (e)nvironment
  description: |
    nspyre is a Python package for conducting scientific experiments. It provides 
    a set of tools to allow for control of instrumentation, data collection, 
    real-time plotting, as well as GUI generation.
  doc_url: https://nspyre.readthedocs.io/
  dev_url: https://github.com/nspyre-org/nspyre

extra:
  recipe-maintainers:
    - jacobfeder
