{% set name = "nspyre" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nspyre-org/nspyre/archive/v{{ version }}.tar.gz
  sha256: 50e61824a0db7f16a805d48ddf60d9d58fe0c738a490a77f57d6a804722393c3

build:
  entry_points:
    - nspyre-dataserv = nspyre.cli.dataserv:_main
    - nspyre-inserv = nspyre.cli.inserv:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - numpy >=1.23.0,<2.0.0
    - rpyc >=5.2.3,<6.0.0
    - pyqt >=5.12.3,<7.0.0
    - pyqtgraph >=0.13.1,<0.14.0
  run_constrained:
    - pre-commit *
    - sphinx *
    - sphinx-copybutton *
    - sphinx_rtd_theme *
    - sphinx-autoapi *
    - pytest *
    - pytest-cov *
    - pint *
    - poetry2setup *

test:
  imports:
    - nspyre
  commands:
    - pip check
    - nspyre-dataserv --help
    - nspyre-inserv --help
  requires:
    - pip

about:
  home: https://github.com/nspyre-org/nspyre
  summary: Networked Scientific Python Research Environment.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobfeder
