{% set name = "nspyre" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-org/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6c10d14c80b80a309d80d5e2253c35e579043f8ca154482c75151c2ea4a31ecf

build:
  noarch: python
  number: 0
  entry_points:
    - nspyre = nspyre.gui:main
    - nspyre-config = nspyre.config:main
    - nspyre-inserv = nspyre.inserv:main
    - nspyre-mongodb = nspyre.mongodb:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pip
    - git
    - hub
    # SciPy
    - numpy
    - scipy
    - pandas
    # MongoDB
    - mongodb >=4.0.3
    - pymongo >=3.10.1
    # Qt
    - pyqt >=5.12.3
    - pyqtgraph
    - qscintilla2
    # VISA
    - pyvisa >=1.10.1
    # Lantz
    - pint
    - pimpmyclass >=0.4.3
    - lantz >=0.6.0
    # Utilities
    - parse >=1.17.0
    - tqdm >=4.48.2
    - rpyc >=4.1.5

test:
  imports:
    - nspyre
    - nspyre.config
    - nspyre.gui
    - nspyre.gui.widgets
    - nspyre.inserv
    - nspyre.misc
    - nspyre.mongodb
#  commands:
#    - nspyre --help
#    - nspyre-config --help
#    - nspyre-inserv --help
#    - nspyre-mongodb --help
  requires:
    - pip

about:
  home: https://github.com/nspyre-org/nspyre
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pythonic Networked Scientific Experimentation Toolkit

  description: |
    NSpyre is a Python Framework for conducting physics experiments.
    It uses a networked approach to allow for the running of experiments 
    using distributed equipment over many networked systems. The 
    experimental hardware being controlled can thus be connected to 
    different computers, which can in turn be controlled by another 
    machine running the experimental commands. This allows for the easy 
    integration of shared resources in a research environment.
  doc_url: https://nspyre.readthedocs.io/
  dev_url: https://github.com/nspyre-org/nspyre

extra:
  recipe-maintainers:
    - mtsolmn
    - jacobfeder
